<?php

namespace ContainerWg1tbZt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8VP1xIDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8VP1xID' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8VP1xID'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'knpSnappyPdf' => ['services', 'knp_snappy.pdf', 'getKnpSnappy_PdfService', true],
        ], [
            'knpSnappyPdf' => '?',
        ]);
    }
}
