<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXQ4nD4M\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXQ4nD4M/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXQ4nD4M.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXQ4nD4M\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXQ4nD4M\App_KernelProdContainer([
    'container.build_hash' => 'XQ4nD4M',
    'container.build_id' => 'b4331b6a',
    'container.build_time' => 1628174408,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXQ4nD4M');
