<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSKfT0Y9\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSKfT0Y9/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSKfT0Y9.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSKfT0Y9\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSKfT0Y9\App_KernelProdContainer([
    'container.build_hash' => 'SKfT0Y9',
    'container.build_id' => '53b7b84b',
    'container.build_time' => 1628099972,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSKfT0Y9');
