<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOx9c5xe\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOx9c5xe/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOx9c5xe.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOx9c5xe\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOx9c5xe\App_KernelProdContainer([
    'container.build_hash' => 'Ox9c5xe',
    'container.build_id' => '083292a1',
    'container.build_time' => 1613477828,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOx9c5xe');
