<?php

namespace ContainerXQ4nD4M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessoireType2TypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AccessoireType2Type' shared autowired service.
     *
     * @return \App\Form\AccessoireType2Type
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AccessoireType2Type'] = new \App\Form\AccessoireType2Type();
    }
}
