<?php

namespace ContainerXQ4nD4M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEchelleAccessoireRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\EchelleAccessoireRepository' shared autowired service.
     *
     * @return \App\Repository\EchelleAccessoireRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EchelleAccessoireRepository'] = new \App\Repository\EchelleAccessoireRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
