register:
    path: /register/{Verification}
    controller: App\Controller\RegistrationController::register

RegisterInvite:
    path: /registerInvite/{id}
    controller: App\Controller\RegistrationController::RegisterInvite
    
index:
    path: /index
    controller: App\Controller\DefaultController::index

login:
    path: /
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    methods: GET

ajout:
    path: /ajout/{verification}
    controller: App\Controller\DefaultController::AjoutConfig

ajoutEchelle:
    path: /ajoutEchelle/{id}
    controller: App\Controller\DefaultController::AjoutEchelle

detailConfig:
    path: /detail/{id}
    controller: App\Controller\DefaultController::detailConfig

ChoixNorme:
    path: /Norme/{id}
    controller: App\Controller\DefaultController::ChoixNorme

ajoutHauteur:
    path: /Hauteur/{id}
    controller: App\Controller\DefaultController::ajoutHauteur

ajoutEntree:
    path: /Entree/{id}
    controller: App\Controller\DefaultController::ajoutEntree

ajoutSortie:
    path: /Sortie/{id}
    controller: App\Controller\DefaultController::ajoutSortie

accessoireAjout:
    path: /Accessoire/{id}
    controller: App\Controller\DefaultController::AjoutAccessoire

ajoutChangementVolee:
    path: /ChangementVolee/{id}
    controller: App\Controller\DefaultController::ajoutChangementVolee

pdf:
    path: /Pdf/{id}
    controller: App\Controller\DefaultController::toPdfAction

ajoutFixation:
    path: /AjoutFixation/{id}
    controller: App\Controller\DefaultController::AjoutFixation

pdf2:
    path: pdf2
    controller: App\Controller\DefaultController::toPdfActionLegend

pdf3:
    path : pdf3
    controller: App\Controller\DefaultController::toPdfActionIncruste

GestionAdmin:
    path : GestionAdmin
    controller: App\Controller\AdminController::GestionAdmin

AdminSupprimerAccessoire:
    path : GestionAdmin/SupprimerAccessoire/{id}
    controller: App\Controller\AdminController::SupprimerAccessoire

AdminModifierAccessoire:
    path : GestionAdmin/ModifierAccessoire/{id}
    controller: App\Controller\AdminController::ModifierAccessoire

AdminCommercialiseAccessoire:
    path : GestionAdmin/CommercialiseAccessoire/{id}
    controller: App\Controller\AdminController::CommercialiseAccessoire

AdminAjouterAccessoire:
    path : GestionAdmin/AjouterAccessoire
    controller: App\Controller\AdminController::AjouterAccessoire

ModifierConfig:
    path : ModifierConfig/{id}
    controller: App\Controller\DefaultController::ModifierConfig