register:
    path: /register/{Verification}
    controller: App\Controller\RegistrationController::register

RegisterInvite:
    path: /registerInvite/{id}
    controller: App\Controller\RegistrationController::RegisterInvite
    
index:
    path: /index
    controller: App\Controller\DefaultController::index

login:
    path: /
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    methods: GET

ajout:
    path: /ajout/{verification}
    controller: App\Controller\DefaultController::AjoutConfig

ajoutEchelle:
    path: /ajoutEchelle/{id}
    controller: App\Controller\DefaultController::AjoutEchelle

detailConfig:
    path: /detail/{id}
    controller: App\Controller\DefaultController::detailConfig

ChoixNorme:
    path: /Norme/{id}
    controller: App\Controller\DefaultController::ChoixNorme

ajoutHauteur:
    path: /Hauteur/{id}
    controller: App\Controller\DefaultController::ajoutHauteur

ajoutEntree:
    path: /Entree/{id}
    controller: App\Controller\DefaultController::ajoutEntree

ajoutSortie:
    path: /Sortie/{id}
    controller: App\Controller\DefaultController::ajoutSortie

accessoireAjout:
    path: /Accessoire/{id}
    controller: App\Controller\DefaultController::AjoutAccessoire

ajoutChangementVolee:
    path: /ChangementVolee/{id}
    controller: App\Controller\DefaultController::ajoutChangementVolee

pdf:
    path: /Pdf/{id}
    controller: App\Controller\DefaultController::toPdfAction

ajoutFixation:
    path: /AjoutFixation/{id}
    controller: App\Controller\DefaultController::AjoutFixation

pdf2:
    path: pdf2
    controller: App\Controller\DefaultController::toPdfActionLegend

pdf3:
    path : pdf3/{id}
    controller: App\Controller\DefaultController::toPdfActionIncruste

GestionAdmin:
    path : GestionAdmin
    controller: App\Controller\AdminController::GestionAdmin

AdminSupprimerAccessoire:
    path : GestionAdmin/SupprimerAccessoire/{id}
    controller: App\Controller\AdminController::SupprimerAccessoire

AdminModifierAccessoire:
    path : GestionAdmin/ModifierAccessoire/{id}
    controller: App\Controller\AdminController::ModifierAccessoire

AdminCommercialiseAccessoire:
    path : GestionAdmin/CommercialiseAccessoire/{id}
    controller: App\Controller\AdminController::CommercialiseAccessoire

AdminAjouterAccessoire:
    path : GestionAdmin/AjouterAccessoire
    controller: App\Controller\AdminController::AjouterAccessoire

ModifierConfig:
    path : ModifierConfig/{id}
    controller: App\Controller\DefaultController::ModifierConfig

AdminSupprimerTypeEchelle:
    path : GestionAdmin/SupprimerTypeEchelle/{id}
    controller: App\Controller\AdminController::SupprimerTypeEchelle

AdminCommercialiseTypeEchelle:
    path : GestionAdmin/CommercialiseTypeEchelle/{id}
    controller: App\Controller\AdminController::CommercialiseTypeEchelle

AdminAjouterTypeEchelle:
    path : GestionAdmin/AjouterTypeEchelle
    controller: App\Controller\AdminController::AjouterTypeEchelle

AdminModifierTypeEchelle:
    path : GestionAdmin/ModifierTypeEchelle/{id}
    controller: App\Controller\AdminController::ModifierTypeEchelle

AdminSupprimerEntree:
    path : GestionAdmin/SupprimerEntree/{id}
    controller: App\Controller\AdminController::SupprimerEntree

AdminCommercialiseEntree:
    path : GestionAdmin/CommercialiseEntree/{id}
    controller: App\Controller\AdminController::CommercialiseEntree

AdminAjouterEntree:
    path : GestionAdmin/AjouterEntree
    controller: App\Controller\AdminController::AjouterEntree

AdminModifierEntree:
    path : GestionAdmin/ModifierEntree/{id}
    controller: App\Controller\AdminController::ModifierEntree


AdminSupprimerSortie:
    path : GestionAdmin/SupprimerSortie/{id}
    controller: App\Controller\AdminController::SupprimerSortie

AdminCommercialiseSortie:
    path : GestionAdmin/CommercialiseSortie/{id}
    controller: App\Controller\AdminController::CommercialiseSortie

AdminAjouterSortie:
    path : GestionAdmin/AjouterSortie
    controller: App\Controller\AdminController::AjouterSortie

AdminModifierSortie:
    path : GestionAdmin/ModifierSortie/{id}
    controller: App\Controller\AdminController::ModifierSortie