<?php

namespace ContainerOx9c5xe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_DefaultEntityManagerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'doctrine.orm.default_entity_manager' shared service.
     *
     * @return \Doctrine\ORM\EntityManager
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->services['doctrine.orm.default_entity_manager'] = $container->createProxy('EntityManager_9a5be93', function () use ($container) {
                return \EntityManager_9a5be93::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        $a = new \Doctrine\ORM\Configuration();

        $b = new \Symfony\Component\Cache\DoctrineProvider(($container->privates['doctrine.system_cache_pool'] ?? $container->load('getDoctrine_SystemCachePoolService')));
        $c = new \Doctrine\Persistence\Mapping\Driver\MappingDriverChain();
        $c->addDriver(new \Doctrine\ORM\Mapping\Driver\AnnotationDriver(($container->privates['annotations.cached_reader'] ?? $container->getAnnotations_CachedReaderService()), [0 => (\dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Entity')]), 'App\\Entity');

        $a->setEntityNamespaces(['App' => 'App\\Entity']);
        $a->setMetadataCacheImpl($b);
        $a->setQueryCacheImpl($b);
        $a->setResultCacheImpl(new \Symfony\Component\Cache\DoctrineProvider(($container->privates['doctrine.result_cache_pool'] ?? $container->load('getDoctrine_ResultCachePoolService'))));
        $a->setMetadataDriverImpl($c);
        $a->setProxyDir(($container->targetDir.''.'/doctrine/orm/Proxies'));
        $a->setProxyNamespace('Proxies');
        $a->setAutoGenerateProxyClasses(false);
        $a->setClassMetadataFactoryName('Doctrine\\ORM\\Mapping\\ClassMetadataFactory');
        $a->setDefaultRepositoryClassName('Doctrine\\ORM\\EntityRepository');
        $a->setNamingStrategy(new \Doctrine\ORM\Mapping\UnderscoreNamingStrategy(0, true));
        $a->setQuoteStrategy(new \Doctrine\ORM\Mapping\DefaultQuoteStrategy());
        $a->setEntityListenerResolver(new \Doctrine\Bundle\DoctrineBundle\Mapping\ContainerEntityListenerResolver($container));
        $a->setRepositoryFactory(new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Repository\\AccessoireRepository' => ['privates', 'App\\Repository\\AccessoireRepository', 'getAccessoireRepositoryService', true],
            'App\\Repository\\ChangementVoleeRepository' => ['privates', 'App\\Repository\\ChangementVoleeRepository', 'getChangementVoleeRepositoryService', true],
            'App\\Repository\\ConfigRepository' => ['privates', 'App\\Repository\\ConfigRepository', 'getConfigRepositoryService', true],
            'App\\Repository\\EchelleAccessoireRepository' => ['privates', 'App\\Repository\\EchelleAccessoireRepository', 'getEchelleAccessoireRepositoryService', true],
            'App\\Repository\\EchelleRepository' => ['privates', 'App\\Repository\\EchelleRepository', 'getEchelleRepositoryService', true],
            'App\\Repository\\ElementRepository' => ['privates', 'App\\Repository\\ElementRepository', 'getElementRepositoryService', true],
            'App\\Repository\\EntreeRepository' => ['privates', 'App\\Repository\\EntreeRepository', 'getEntreeRepositoryService', true],
            'App\\Repository\\FixationRepository' => ['privates', 'App\\Repository\\FixationRepository', 'getFixationRepositoryService', true],
            'App\\Repository\\HauteurRepository' => ['privates', 'App\\Repository\\HauteurRepository', 'getHauteurRepositoryService', true],
            'App\\Repository\\NormeRepository' => ['privates', 'App\\Repository\\NormeRepository', 'getNormeRepositoryService', true],
            'App\\Repository\\PalierRepository' => ['privates', 'App\\Repository\\PalierRepository', 'getPalierRepositoryService', true],
            'App\\Repository\\ProductRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'App\\Repository\\RoleRepository' => ['privates', 'App\\Repository\\RoleRepository', 'getRoleRepositoryService', true],
            'App\\Repository\\SortieRepository' => ['privates', 'App\\Repository\\SortieRepository', 'getSortieRepositoryService', true],
            'App\\Repository\\TypeEchelleRepository' => ['privates', 'App\\Repository\\TypeEchelleRepository', 'getTypeEchelleRepositoryService', true],
            'App\\Repository\\UserRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'App\\Repository\\UtilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'App\\Repository\\AccessoireRepository' => '?',
            'App\\Repository\\ChangementVoleeRepository' => '?',
            'App\\Repository\\ConfigRepository' => '?',
            'App\\Repository\\EchelleAccessoireRepository' => '?',
            'App\\Repository\\EchelleRepository' => '?',
            'App\\Repository\\ElementRepository' => '?',
            'App\\Repository\\EntreeRepository' => '?',
            'App\\Repository\\FixationRepository' => '?',
            'App\\Repository\\HauteurRepository' => '?',
            'App\\Repository\\NormeRepository' => '?',
            'App\\Repository\\PalierRepository' => '?',
            'App\\Repository\\ProductRepository' => '?',
            'App\\Repository\\RoleRepository' => '?',
            'App\\Repository\\SortieRepository' => '?',
            'App\\Repository\\TypeEchelleRepository' => '?',
            'App\\Repository\\UserRepository' => '?',
            'App\\Repository\\UtilisateurRepository' => '?',
        ])));

        $instance = \Doctrine\ORM\EntityManager::create(($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService')), $a);

        (new \Doctrine\Bundle\DoctrineBundle\ManagerConfigurator([], []))->configure($instance);

        return $instance;
    }
}
