<?php

namespace ContainerOx9c5xe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntreeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\EntreeRepository' shared autowired service.
     *
     * @return \App\Repository\EntreeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EntreeRepository'] = new \App\Repository\EntreeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
