<?php

namespace ContainerOx9c5xe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNormeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\NormeRepository' shared autowired service.
     *
     * @return \App\Repository\NormeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\NormeRepository'] = new \App\Repository\NormeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
