<?php

namespace ContainerSKfT0Y9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFixationTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\FixationType' shared autowired service.
     *
     * @return \App\Form\FixationType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\FixationType'] = new \App\Form\FixationType();
    }
}
