<?php

namespace ContainerSKfT0Y9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNormeTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\NormeType' shared autowired service.
     *
     * @return \App\Form\NormeType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\NormeType'] = new \App\Form\NormeType();
    }
}
