<?php

namespace ContainerSKfT0Y9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSortieTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\SortieType' shared autowired service.
     *
     * @return \App\Form\SortieType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SortieType'] = new \App\Form\SortieType();
    }
}
