<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWg1tbZt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWg1tbZt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWg1tbZt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWg1tbZt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWg1tbZt\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wg1tbZt',
    'container.build_id' => 'e8bf34a7',
    'container.build_time' => 1628182072,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWg1tbZt');
