<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPmDy2pb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPmDy2pb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPmDy2pb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPmDy2pb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPmDy2pb\App_KernelDevDebugContainer([
    'container.build_hash' => 'PmDy2pb',
    'container.build_id' => '6b60dead',
    'container.build_time' => 1628175822,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPmDy2pb');
