<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN1CkNtz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN1CkNtz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN1CkNtz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN1CkNtz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN1CkNtz\App_KernelDevDebugContainer([
    'container.build_hash' => 'N1CkNtz',
    'container.build_id' => '261bfb42',
    'container.build_time' => 1626444768,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN1CkNtz');
