<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Echelle extends \App\Entity\Echelle implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'echelleSortie', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'echelleEntree', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'echelleHauteur', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'echelleTypeEchelle', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'echelleNorme', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'echelleConfig', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'changementVolee', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'EchelleFixation', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'palier', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'EchelleAccessoire', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'coupeEchelleEchelles'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'echelleSortie', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'echelleEntree', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'echelleHauteur', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'echelleTypeEchelle', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'echelleNorme', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'echelleConfig', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'changementVolee', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'EchelleFixation', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'palier', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'EchelleAccessoire', '' . "\0" . 'App\\Entity\\Echelle' . "\0" . 'coupeEchelleEchelles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Echelle $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEchelleSortie(): ?\App\Entity\Sortie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEchelleSortie', []);

        return parent::getEchelleSortie();
    }

    /**
     * {@inheritDoc}
     */
    public function setEchelleSortie(?\App\Entity\Sortie $echelleSortie): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEchelleSortie', [$echelleSortie]);

        return parent::setEchelleSortie($echelleSortie);
    }

    /**
     * {@inheritDoc}
     */
    public function getEchelleEntree(): ?\App\Entity\Entree
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEchelleEntree', []);

        return parent::getEchelleEntree();
    }

    /**
     * {@inheritDoc}
     */
    public function setEchelleEntree(?\App\Entity\Entree $echelleEntree): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEchelleEntree', [$echelleEntree]);

        return parent::setEchelleEntree($echelleEntree);
    }

    /**
     * {@inheritDoc}
     */
    public function getEchelleHauteur(): ?\App\Entity\Hauteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEchelleHauteur', []);

        return parent::getEchelleHauteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setEchelleHauteur(?\App\Entity\Hauteur $echelleHauteur): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEchelleHauteur', [$echelleHauteur]);

        return parent::setEchelleHauteur($echelleHauteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getEchelleTypeEchelle(): ?\App\Entity\TypeEchelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEchelleTypeEchelle', []);

        return parent::getEchelleTypeEchelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setEchelleTypeEchelle(?\App\Entity\TypeEchelle $echelleTypeEchelle): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEchelleTypeEchelle', [$echelleTypeEchelle]);

        return parent::setEchelleTypeEchelle($echelleTypeEchelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getEchelleNorme(): ?\App\Entity\Norme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEchelleNorme', []);

        return parent::getEchelleNorme();
    }

    /**
     * {@inheritDoc}
     */
    public function setEchelleNorme(?\App\Entity\Norme $echelleNorme): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEchelleNorme', [$echelleNorme]);

        return parent::setEchelleNorme($echelleNorme);
    }

    /**
     * {@inheritDoc}
     */
    public function getEchelleConfig(): ?\App\Entity\Config
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEchelleConfig', []);

        return parent::getEchelleConfig();
    }

    /**
     * {@inheritDoc}
     */
    public function setEchelleConfig(?\App\Entity\Config $echelleConfig): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEchelleConfig', [$echelleConfig]);

        return parent::setEchelleConfig($echelleConfig);
    }

    /**
     * {@inheritDoc}
     */
    public function getChangementVolee(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChangementVolee', []);

        return parent::getChangementVolee();
    }

    /**
     * {@inheritDoc}
     */
    public function addChangementVolee(\App\Entity\ChangementVolee $changementVolee): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChangementVolee', [$changementVolee]);

        return parent::addChangementVolee($changementVolee);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChangementVolee(\App\Entity\ChangementVolee $changementVolee): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChangementVolee', [$changementVolee]);

        return parent::removeChangementVolee($changementVolee);
    }

    /**
     * {@inheritDoc}
     */
    public function getPalier(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPalier', []);

        return parent::getPalier();
    }

    /**
     * {@inheritDoc}
     */
    public function addPalier(\App\Entity\Palier $palier): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPalier', [$palier]);

        return parent::addPalier($palier);
    }

    /**
     * {@inheritDoc}
     */
    public function removePalier(\App\Entity\Palier $palier): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePalier', [$palier]);

        return parent::removePalier($palier);
    }

    /**
     * {@inheritDoc}
     */
    public function getEchelleAccessoire(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEchelleAccessoire', []);

        return parent::getEchelleAccessoire();
    }

    /**
     * {@inheritDoc}
     */
    public function setEchelleAccessoire(\Doctrine\Common\Collections\Collection $EchelleAccessoire): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEchelleAccessoire', [$EchelleAccessoire]);

        return parent::setEchelleAccessoire($EchelleAccessoire);
    }

    /**
     * {@inheritDoc}
     */
    public function addEchelleAccessoire(\App\Entity\EchelleAccessoire $EchelleAccessoire): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEchelleAccessoire', [$EchelleAccessoire]);

        return parent::addEchelleAccessoire($EchelleAccessoire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEchelleAccessoire(\App\Entity\EchelleAccessoire $EchelleAccessoire): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEchelleAccessoire', [$EchelleAccessoire]);

        return parent::removeEchelleAccessoire($EchelleAccessoire);
    }

    /**
     * {@inheritDoc}
     */
    public function getEchelleFixation(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEchelleFixation', []);

        return parent::getEchelleFixation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEchelleFixation(\Doctrine\Common\Collections\Collection $EchelleFixation): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEchelleFixation', [$EchelleFixation]);

        return parent::setEchelleFixation($EchelleFixation);
    }

    /**
     * {@inheritDoc}
     */
    public function addEchelleFixation(\App\Entity\EchelleFixation $EchelleFixation): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEchelleFixation', [$EchelleFixation]);

        return parent::addEchelleFixation($EchelleFixation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEchelleFixation(\App\Entity\EchelleFixation $EchelleFixation): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEchelleFixation', [$EchelleFixation]);

        return parent::removeEchelleFixation($EchelleFixation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoupeEchelleEchelles(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoupeEchelleEchelles', []);

        return parent::getCoupeEchelleEchelles();
    }

    /**
     * {@inheritDoc}
     */
    public function addCoupeEchelleEchelle(\App\Entity\CoupeEchelleEchelle $coupeEchelleEchelle): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCoupeEchelleEchelle', [$coupeEchelleEchelle]);

        return parent::addCoupeEchelleEchelle($coupeEchelleEchelle);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCoupeEchelleEchelle(\App\Entity\CoupeEchelleEchelle $coupeEchelleEchelle): \App\Entity\Echelle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCoupeEchelleEchelle', [$coupeEchelleEchelle]);

        return parent::removeCoupeEchelleEchelle($coupeEchelleEchelle);
    }

}
